# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20180203_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemManager',
        ),
    ]
