# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_delete_itemmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='starting_bid',
        ),
    ]
