# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_item_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auction.User'),
        ),
    ]
